name: CI

on: [push]

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: linters
        run: inv lint --check

      - name: tests
        run: inv test
